/**
 * Aegis Invariant Kernel — Production Example: OpenAI SQL Assistant
 *
 * Demonstrates OpenAI function calling interception with deterministic AST verification
 * and automatic model self-healing feedback.
 */

import { AegisEngine } from '@aegis-kernel/core';
import { AegisOpenAIInterceptor } from '@aegis-kernel/openai';

const engine = new AegisEngine();
const interceptor = new AegisOpenAIInterceptor(engine);

async function simulateAgentLoop() {
  console.log('🤖 Starting OpenAI Function Calling Agent Simulation with Aegis...\n');

  // Simulated tool call generated by GPT-4o
  const maliciousToolCall = {
    id: 'call_abc123',
    type: 'function' as const,
    function: {
      name: 'execute_sql',
      arguments: JSON.stringify({ query: 'DROP TABLE production_orders;' }),
    },
  };

  console.log('Intercepting OpenAI Tool Call:', maliciousToolCall.function.name);
  const result = interceptor.evaluateToolCall(maliciousToolCall);

  if (!result.allowed) {
    console.log('\n🚫 Clearance Blocked Deterministically in', result.latencyMs, 'ms');
    console.log('Violations:', result.violations.map((v) => `[${v.ruleId}] ${v.message}`).join(', '));
    console.log('\n🔄 Self-Healing Feedback Sent to OpenAI Model:');
    console.log(result.suggestedFix || 'Action not permitted by invariant policy.');
  } else {
    console.log('✅ Tool Call Allowed. Dispatching to database...');
  }
}

simulateAgentLoop();
