#!/usr/bin/env node
/**
 * Generate packages/core/src/packs.generated.ts from the YAML pack files.
 *
 * The YAML files in packages/core/packs/ are the single source of truth.
 * This script embeds their raw contents as strings so BUILTIN_PACKS works
 * in ANY environment (bundled CLI, GitHub Action, esbuild consumers) with
 * zero filesystem dependency and zero drift by construction.
 *
 * pack-governance.test.ts fails CI if the YAMLs ever diverge from the
 * generated module (i.e., someone edits a YAML without re-running this).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';

const ROOT = path.resolve(import.meta.dirname, '..');
const PACKS_DIR = path.join(ROOT, 'packages', 'core', 'packs');
const OUT = path.join(ROOT, 'packages', 'core', 'src', 'packs.generated.ts');

const files = fs.readdirSync(PACKS_DIR).filter((f) => f.endsWith('.yaml')).sort();
const entries = files.map((f) => {
  const content = fs.readFileSync(path.join(PACKS_DIR, f), 'utf8');
  const escaped = JSON.stringify(content);
  const id = f.replace(/\.yaml$/, '');
  return `  '@aegis/${id}': ${escaped},`;
});

const header = `// AUTO-GENERATED by scripts/gen-packs.mjs — DO NOT EDIT BY HAND.
// Source of truth: packages/core/packs/*.yaml (run \`npm run gen:packs\` after editing).

export const EMBEDDED_PACK_YAMLS: Record<string, string> = {
${entries.join('\n')}
};
`;

fs.writeFileSync(OUT, header);
let sha = 'unknown';
try { sha = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim(); } catch { /* not a git repo */ }
console.log(`packs.generated.ts: ${files.length} packs embedded (git ${sha})`);
