#!/usr/bin/env bash
#
# Independent auditor verification for the sample evidence bundle generated by
# scripts/generate-sample-audit-reports.mjs.
#
# Re-hashes every WORM object on disk against the SHA-256 digests recorded in
# worm-manifest.json and recomputes the chain-of-custody link hashes. Uses only
# sha256sum + jq (no project code), so it is independent of the Aegis runtime.
#
# Usage: bash scripts/verify-sample-audit-reports.sh
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$HERE/../examples/audit-reports"
MANIFEST="$OUT_DIR/worm-manifest.json"
WORM_DIR="$OUT_DIR/worm-objects"

if [[ ! -f "$MANIFEST" ]]; then
  echo "✗ worm-manifest.json not found. Run scripts/generate-sample-audit-reports.mjs first." >&2
  exit 1
fi

echo "== Verifying WORM object integrity against manifest =="
fail=0

# 1. Re-hash every file listed in the manifest.
jq -r '.files[] | .key + "  " + .sha256' "$MANIFEST" | while IFS='  ' read -r key expected; do
  # strip the leading key prefix (e.g. aegis-compliance/) to locate on disk
  rel="${key#aegis-compliance/}"
  file="$WORM_DIR/$rel"
  if [[ ! -f "$file" ]]; then
    echo "  ✗ MISSING $key"
    echo "FAIL" > "$OUT_DIR/.verify-failed"
    continue
  fi
  actual="$(sha256sum "$file" | awk '{print $1}')"
  if [[ "$actual" == "$expected" ]]; then
    echo "  ✓ $key"
  else
    echo "  ✗ HASH MISMATCH $key (expected $expected, got $actual)"
    echo "FAIL" > "$OUT_DIR/.verify-failed"
  fi
done

# 2. Recompute the chain-of-custody link hashes.
echo "== Recomputing chain-of-custody =="
prev="$(printf '0%.0s' {1..64})"
jq -c '.chainOfCustody[]' "$MANIFEST" | while read -r entry; do
  seq="$(echo "$entry" | jq -r '.sequence')"
  key="$(echo "$entry" | jq -r '.fileKey')"
  sha="$(echo "$entry" | jq -r '.sha256')"
  expected="$(echo "$entry" | jq -r '.entryHash')"
  # link hash = sha256("seq:key:sha256:prev")
  actual="$(printf '%s:%s:%s:%s' "$seq" "$key" "$sha" "$prev" | sha256sum | awk '{print $1}')"
  if [[ "$actual" == "$expected" ]]; then
    echo "  ✓ seq $seq ($key)"
  else
    echo "  ✗ CHAIN BREAK at seq $seq ($key)"
    echo "FAIL" > "$OUT_DIR/.verify-failed"
  fi
  prev="$expected"
done

if [[ -f "$OUT_DIR/.verify-failed" ]]; then
  rm -f "$OUT_DIR/.verify-failed"
  echo ""
  echo "RESULT: FAIL — one or more integrity checks did not match."
  exit 1
fi

echo ""
echo "RESULT: PASS — all WORM objects and chain-of-custody links verified."
