name: Hadolint Container Image Dockerfile Linting

on:
  push:
    paths:
      - '**/Dockerfile*'
      - '.github/workflows/hadolint.yml'
  pull_request:
    paths:
      - '**/Dockerfile*'
  workflow_dispatch:

permissions: read-all

jobs:
  hadolint:
    name: Hadolint Best Practice & Security Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Lint Gateway Dockerfile
        uses: hadolint/hadolint-action@v3.4.0
        with:
          dockerfile: 'services/gateway/Dockerfile'
          ignore: 'DL3018,DL3008'
